
###
GET http://dungbeetles.xyz:3410/devices/regions?account=CSCB001

###
GET http://dungbeetles.xyz:3410/devices/ids?account=CSCB001


###
POST http://localhost:3410/app/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="chntek-1.0.0.apk"
Content-Type: application/octet-stream

< ./chntek-1.0.0.apk
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
GET http://localhost:3410/app/latest

###
GET http://iot.chntek.com:3410/api/user/login
?account=test
&password=123

###查询所有区域设备
GET http://iot.chntek.com:3410/api/Terminal/Regions
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidGVzdCIsImV4cCI6MTYxMjQ4NjE5OCwiaXNzIjoiSnd0S2V5TmFtZSIsImF1ZCI6Ikp3dEtleU5hbWUifQ.--VK2JdU8IgkgnjyQ9Kck_22McjIEgaf2FkhNDjjNEE



###查询所有设备
GET http://iot.chntek.com:3410/api/Terminal/GetAllDevice
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidGVzdCIsImV4cCI6MTYxMTUwMDM3NCwiaXNzIjoiSnd0S2V5TmFtZSIsImF1ZCI6Ikp3dEtleU5hbWUifQ.8nnKmig8Ar5uAC5WDZLxJZEl9mEpPsqbN4YrBt-H_UQ

###查询设备状态
GET http://iot.chntek.com:3410/api/Terminal/HistoryData
    ?ids=CSCB0000001,CSCB0000002,CSCB0000003,CSCB0000004,CSCB0000005,CSCB0000006,CSCB0000007,CSCB0000008,CSCB0000009,CSCB0000010,CSCB0000011,CSCB0000012
    &date_begin=2021-01-04
    &date_end=2021-01-05
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidGVzdCIsImV4cCI6MTYxMTUwMDM3NCwiaXNzIjoiSnd0S2V5TmFtZSIsImF1ZCI6Ikp3dEtleU5hbWUifQ.8nnKmig8Ar5uAC5WDZLxJZEl9mEpPsqbN4YrBt-H_UQ

###查询告警状态
GET http://iot.chntek.com:3410/api/Terminal/RealTimeData
    ?searchDate=2021-1-05
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidGVzdCIsImV4cCI6MTYxMTUwMDM3NCwiaXNzIjoiSnd0S2V5TmFtZSIsImF1ZCI6Ikp3dEtleU5hbWUifQ.8nnKmig8Ar5uAC5WDZLxJZEl9mEpPsqbN4YrBt-H_UQ
