
###
GET http://dungbeetles.xyz:3410/devices/regions?account=CSCB001

###
GET http://dungbeetles.xyz:3410/devices/ids?account=CSCB001

###
GET http://dungbeetles.xyz:3410/devices/primary?ids=CSCB0000001

###
GET http://localhost:3410/devices/status-history?id=CSCB0000001&size=20&date_begin=2021-01-04&date_end=2021-01-27

###
GET http://dungbeetles.xyz:3410/devices/warnings?id=CSCB0000001&date=2021-02-03&size=1

###
POST http://dungbeetles.xyz:3410/app/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="chntek-1.1.3.apk"
Content-Type: application/octet-stream

< C:\Users\SLTru\Desktop\chntek-fire-fighting\app\platforms\android\app\build\outputs\apk\debug\app-debug.apk
------WebKitFormBoundary7MA4YWxkTrZu0gW--


###
GET http://dungbeetles.xyz:3410/app/latest

###登录
GET http://iot.chntek.com:3410/api/user/login
?account=cscb001
&password=123

###查询所有区域设备
GET http://iot.chntek.com:3410/api/Terminal/Regions
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidGVzdCIsImV4cCI6MTYxMjQ4NjE5OCwiaXNzIjoiSnd0S2V5TmFtZSIsImF1ZCI6Ikp3dEtleU5hbWUifQ.--VK2JdU8IgkgnjyQ9Kck_22McjIEgaf2FkhNDjjNEE



###查询所有设备
GET http://iot.chntek.com:3410/api/Terminal/GetAllDevice
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidGVzdCIsImV4cCI6MTYxMTUwMDM3NCwiaXNzIjoiSnd0S2V5TmFtZSIsImF1ZCI6Ikp3dEtleU5hbWUifQ.8nnKmig8Ar5uAC5WDZLxJZEl9mEpPsqbN4YrBt-H_UQ

###查询设备状态
GET http://iot.chntek.com:3410/api/Terminal/HistoryData
    ?ids=LYGS000004
    &date_begin=2021-01-01
    &date_end=2021-03-10
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiQ1NDQjAwMSIsImV4cCI6MTYxNjE1OTU2NCwiaXNzIjoiSnd0S2V5TmFtZSIsImF1ZCI6Ikp3dEtleU5hbWUifQ.ZIMoz8z0cOv3ovkWV8lUwXcz7fEqJcRw31BejPTshpc


###查询告警状态
# 11: 'WorkpiecName', // 信号低报警
# 10: 'InsideDiameter', // 负温标志
# 9: 'HighLevel', // 压力传感器故障报警
# 8: 'lowPosition', // 电量
# 7: 'AvegInside', // 振动
# 6: 'BasicValue', // 倾斜
# 5: 'HighTemp', // 高温
# 4: 'LowTemp', // 低温
# 3: 'Calibraloca', // 漏水/取水
# 2: 'HighPressure', // 高水压
# 1: 'LowPressure', // 低水压
GET http://iot.chntek.com:3410/api/Terminal/RealTimeData
    ?searchDate=2021-2-19
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiQ1NDQjAwMSIsImV4cCI6MTYxNjE1OTU2NCwiaXNzIjoiSnd0S2V5TmFtZSIsImF1ZCI6Ikp3dEtleU5hbWUifQ.ZIMoz8z0cOv3ovkWV8lUwXcz7fEqJcRw31BejPTshpc


###
POST http://iot.chntek.com:3411/app/upload
#POST http://dungbeetles.xyz:3410/app/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="chntek-1.1.5.apk"
Content-Type: application/octet-stream

< C:\Users\SLTru\Desktop\chntek-fire-fighting\app\platforms\android\app\build\outputs\apk\debug\app-debug.apk
------WebKitFormBoundary7MA4YWxkTrZu0gW--