
###查询所有区域设备
GET http://iot.chntek.com:3410/api/Terminal/Regions
Authorization: 12

###查询所有设备
GET http://iot.chntek.com:3410/api/Terminal/GetAllDevice
Authorization: 12

###查询设备状态
GET http://iot.chntek.com:3410/api/Terminal/HistoryData
    ?ids=00006,00018,00017
    &date_begin=2020-12-06
    &date_end=2020-12-08
Authorization: 12

###查询告警状态
GET http://iot.chntek.com:3410/api/Terminal/RealTimeData
    ?searchDate=2020-12-01
Authorization: 12
